// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: halloween

#ifndef _HALLOWEEN_UI_H
#define _HALLOWEEN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image4;
void ui_event_tikvi2( lv_event_t * e);
extern lv_obj_t *ui_tikvi2;
extern lv_obj_t *ui_t2press;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Roller2;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_h240320_png);   // assets\h240320.png
LV_IMG_DECLARE( ui_img_2tikvi_png);   // assets\2tikvi.png
LV_IMG_DECLARE( ui_img_2tikvi_pressed_png);   // assets\2tikvi_pressed.png
LV_IMG_DECLARE( ui_img_t1_png);   // assets\t1.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
