// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: halloween

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image4 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image4, &ui_img_h240320_png);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 239
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 319
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_tikvi2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_tikvi2, &ui_img_2tikvi_png);
lv_obj_set_width( ui_tikvi2, LV_SIZE_CONTENT);  /// 76
lv_obj_set_height( ui_tikvi2, LV_SIZE_CONTENT);   /// 74
lv_obj_set_x( ui_tikvi2, 81 );
lv_obj_set_y( ui_tikvi2, 122 );
lv_obj_set_align( ui_tikvi2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_tikvi2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_tikvi2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_tikvi2, &ui_img_2tikvi_pressed_png, LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_color(ui_tikvi2, lv_color_hex(0xE35B24), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_tikvi2, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_tikvi2, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_tikvi2, 4, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor(ui_tikvi2, lv_color_hex(0xB38383), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_tikvi2, 0, LV_PART_MAIN| LV_STATE_PRESSED);

ui_t2press = lv_img_create(ui_Screen1);
lv_img_set_src(ui_t2press, &ui_img_2tikvi_pressed_png);
lv_obj_set_width( ui_t2press, LV_SIZE_CONTENT);  /// 76
lv_obj_set_height( ui_t2press, LV_SIZE_CONTENT);   /// 74
lv_obj_set_x( ui_t2press, 81 );
lv_obj_set_y( ui_t2press, 123 );
lv_obj_set_align( ui_t2press, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_t2press,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_t2press, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_t2press, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_t2press, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_tikvi2, ui_event_tikvi2, LV_EVENT_ALL, NULL);

}
